name: pushtomain

# ----- workflow runs on push to the main branch.
on:
  push:
    branches:
      - 'main'
      
  workflow_dispatch:

jobs:

# ----- will run if the push did not come from a PR Merge
  pushtomain:
    name: Fail if push directly to main.
    if: "!contains(github.event.head_commit.message, 'Merge pull request')"
    runs-on: ubuntu-latest
    steps:
      - name: do not push to main
        run: |
          echo "In the future do not push directly to main"
          exit 1

# ----- Will run if the push came from a PR Merge
  PRPushtoMain:
    name: Succeed if Push from PR Merge
    if: "contains(github.event.head_commit.message, 'Merge pull request')"
    runs-on: ubuntu-latest
    steps:
      - name: push from PR Merge
        run: echo "Push from PR Merge...."